### ISSUE TITLE
Question regarding "fastReID + RGT&RGPR(ours) 86.2 65.9"

### ISSUE THREAD

**Issue by nixingyang** [finger-monkey/Data-Augmentation#4]
Thanks for publishing the source code.
I am conducting experiments using your method, and I have a question regarding "fastReID + RGT&RGPR(ours) 86.2 65.9" in Table 2:
Are you using the following sequential pipeline for data augmentation:
1, Add random erasing with probability 0.5.
2, Add RGT with probability 0.05.
3, Add RGPR with probability 0.4.
All the best.

**Comment by finger-monkey** [comment]
> Thanks for publishing the source code.
> I am conducting experiments using your method, and I have a question regarding "fastReID + RGT&RGPR(ours) 86.2 65.9" in Table 2:
> Are you using the following sequential pipeline for data augmentation:
> 1, Add random erasing with probability 0.5.
> 2, Add RGT with probability 0.05.
> 3, Add RGPR with probability 0.4.
> All the best.

hi, the “autoAug” of FastReid should be turned off first. The rest, such as random erasing, can be used together。

**Comment by finger-monkey** [comment]
@nixingyang 
I do not know whether your experiment has verified the above experimental results.
If you have any questions during the experiment, please feel free to communicate.

**Comment by AlphaPlusTT** [comment]
@nixingyang hi, i wonder where is the RGT you mentioned in your question? I can only find RGPR in this project now

**Comment by nixingyang** [comment]
@AlphaPlusTT Hi, you can use [ToGray](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.ToGray).
