### ISSUE TITLE
where is the RGTP?

### ISSUE THREAD

**Issue by AlphaPlusTT** [finger-monkey/Data-Augmentation#5]
I can't find the **RGTP** mentioned in your README.md:
(3)add the code between lines 76-77 of 'train.py' file:'transforms.RandomGrayscale(0.05)' or '**RGTP**(0.4)'

and how can i get the **RGT** transform?

**Comment by finger-monkey** [comment]
In fact, RGTP is a plug-and-play method. Please download the code I provided "trans_gray.py" and use it with "import trans_gray.RGPR".   RGTP was a mistake,  forgive my carelessness.

**Comment by finger-monkey** [comment]
The code corresponding to this paper has been continuously updated and improved. Please refer to the latest version of the paper for the most recent information.
