### ISSUE TITLE
How to use GGT and LGT for cross-domain evaluation?

### ISSUE THREAD

**Issue by liyuke65535** [finger-monkey/Data-Augmentation#7]
In “Eliminate Deviation with Deviation for Data Augmentation and a General Multi-modal Data Learning Method”， Table 4 and 6 show that GGT and LGT help the cross-domain task. What's your ratio of GGT? How many images turn into grayscale in training?

**Comment by liyuke65535** [comment]
![image](https://user-images.githubusercontent.com/39180877/198524563-c3242496-bac7-493b-89d5-062c8ef5efe2.png)
![image](https://user-images.githubusercontent.com/39180877/198524596-a109a5e3-4190-4302-b35a-13c819a001e9.png)

**Comment by finger-monkey** [comment]
I'm sorry for the delayed response; I haven't checked my Gmail inbox for a while. Cross-domain testing involves training a model M using the proposed methods on the Market1501 dataset, and then testing the model using dataset Duke with model A. This experiment is relatively easy to implement, and you can try using the baselines mentioned in the paper. All of these are discussed in the paper.
