### ISSUE TITLE
Augmentation Order

### ISSUE THREAD

**Issue by danielsyahputra** [finger-monkey/Data-Augmentation#8]
Hi @finger-monkey 

Is there any constraint related to the LGT method's augmentation order? Like should we use it before or after normalization?

**Comment by finger-monkey** [comment]
To implement this, simply use it in the preprocessing stage of the image before normalization. I apologize for the delayed response; I've been out of research for quite some time.

**Comment by danielsyahputra** [comment]
Thanks for your feedback. Noted for my next experiment.
